# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bfd31671e5375c0369b9d951e49b9985e58ecb0e89b495fc0295b62d726aa5ef175b5a385b51abea863d4548052869fa419a030b77562817b21c77d1ad19cd1

test:
  secret_key_base: c5cfaf340cad7da0a6edfa3983ee62c4df4d007c2e23ff5524922bb106f7cb106dd3ea188e494147f40a02ae7fac336772023347d24fe1c910b995135105d499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
